---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

resources:
  - cinder-pure-container.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cinder-container-values
      fieldPath: data.cinderVolumeImages.pure-fc
    targets:
      - select:
          kind: OpenStackVersion
        fieldPaths:
          - spec.customContainerImages.cinderVolumeImages.pure-fc
        options:
          create: true
